# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: 한재원
title: Back-end Developer
email: point1054@naver.com
phone: 010-4593-1737
website: dodo1054.tistory.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  han-archon

# About Section
about_title: Han Jaewon Introduce
about_profile_image: images/profile.jpg
about_content: | 
  안녕하세요 백엔드 개발자로 일하고 있는 한재원 입니다. <br>
  협업 시 의사소통과 팀원들 간의 일정 및 업무 공유를 중요하게 생각하고, <br>
  실무를 경험하며 협업능력과 개발능력을 기르고 있습니다. <br>
  리팅 성형외과 병원 신규 고객관리프로그램(CRM) 프로젝트 개발 경험과 <br>
  데이팅 앱 서비스인 너랑나랑 및 연권 앱 유지보수 및 신규개발 경험을 하고 있습니다. <br>
  
  긍정적으로 잘 웃는 성격이며 어느 환경에서든 조직에 잘 적응하며 <br>
  새로운 기술에 대해 거부감 없이 접근하고 생각하기 때문에 늘 성장할 수 있는 개발자가 될 수 있습니다.
content:
  - title: Skils # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
        description: | # this will include new lines to allow paragraphs
          - <mark>PHP</mark> <mark>Javascript(jQuery)</mark> <mark>Java(SpringBoot)</mark> 
          - <mark>Nginx</mark> <mark>Apache</mark>
          - <mark>Mysql</mark>   
          - <mark>AWS</mark> <mark>Git</mark> <mark>Jira</mark> <mark>Confluence</mark> <mark>Slack</mark>
          <p> </p> 
          <br>
          
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 테크랩스 
        link: https://www.techlabs.co.kr/
        sub_title: Junior Backend Developer
        caption: 2021-02 ~ 현재
        description: | # this will include new lines to allow paragraphs
          <h2> 너랑나랑 및 연권 서비스 [ 2022.10 - 현재 ]</h2> <br> 
          <h4> Description </h4>
            <p> 너랑나랑 및 연권 서비스 사용성 향상을 위해 유지보수 및 API 개선하였습니다.</p>
          <h4> Work </h4>
            - 기존 FTP -> API 코드 형상관리를 위한 Git 적용 
            - 쿠폰 이벤트 기능 API 개발 
            - 쿠팡 오퍼월 API 개발
            - 너랑나랑 및 연권 AWS -> IDC 서버이전 (Mysql 5.6 -> 8.0 Migration, API 및 CMS 서버 분리) 
            - Slow Query 튜닝
            - CMS 운영 사용성 개선 
            - 서비스 잔존 버그 개선 및 처리
          <h4>Tech Stack</h4>
          - <mark>PHP</mark> <mark>JavaScript</mark> <mark>Nginx</mark> <mark>Apache</mark> 
          - <mark>Mysql</mark> <mark>AWS</mark> <mark>Zeppelin</mark>

          <br>

          <h2> 리팅성형외과 고객관리 프로그램 개발  하였으며 하루 약 1000 건 정도의 예약방문 고객 병원 납품</h2>  
          <h2> 2021.05 - 2022.09 </h2> 
          <h4> Description </h4>
            <p> 리팅성형외과 병원고객관리 프로그램 프로젝트 신규 개발 및 유지보수</p>
          <h4> Work </h4>
            - 예약, 상담, 진료, 수납 연동 Flow API 개발
            - 예약, 상담, 진료, 수납 고객 관련 통계 페이지 개발   
            - 비즈뿌리오 SMS API 개발 및 병원 서비스 내 예약관리 기능과 연동
            - 한국정보인증 전자서명 API 개발 및 병원 서비스 진료관리 기능과 연동  
            - AWS 클라우드 서버 구성 [EC2, RDS, ELB, route53, AutoScaling, S3]
            - 병원 서비스 내 고객 차트 및 이미지 AWS S3 스토리지 연동 API 개발 [Upload, Read, Copy, Delete] 
            - ERD 관리 및 일부기능 DB 설계 참여
            - 약 150만 건의 병원 Data Migration 스크립트 개발 [데이터 한글 -> 코드값 변환 및 분리] 
            - 프로젝트 일정관리 및 Git 관리 
          <h4>Tech Stack</h4>
          - <mark>PHP</mark> <mark>SpringBoot</mark> <mark>JavaScript</mark> <mark>CSS</mark> <mark>Apache</mark> 
          - <mark>Mysql</mark> <mark>AWS</mark> <mark>Kendo UI Framework</mark>

          <br>
          
          <h2> 리팅성형외과 구환관리 통계 페이지 개발 3주만에 완료하여 병원 실적 보고서 데이터기반으로 쓰이고 있음 </h2> 
          <h2> 2021.04 - 2021.05 </h2>
          <h4> Description </h4>
            <p> 리팅성형외과 구환(병원 진료 고객) 관리자 페이지 신규 개발</p>
          <h4> Work </h4>
            - 관리자 매출 통계 페이지 개발
            - 관리자 진료, 상담, 콜, 수납 통계 페이지 개발
            - 고객 진료일 및 수술일 관련 통계 페이지 개발 
          <h4>Tech Stack</h4>
          - <mark>PHP</mark> <mark>JavaScript</mark> <mark>CSS</mark> 
          -  <mark>Kendo UI Framework</mark>
  - title: ETC # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Blog 
        link: dodo1054.tistory.com
        sub_title: 개인 기록용 블로그
        caption: 2019 ~ 현재
        description: |
          <p> 블로그를 한번 헤볼까? 라는 생각으로 개인 기록용으로 사용하고 운영하는 블로그 입니다. <br>
              개인적으로 실천했던 부분들이나 개발하면서 기록이 필요하다고 생각되는 부분들을 기록하고 <br>
              다른 사람들이 참고하여 도움을 줄 수 있도록 만 노력하고 있습니다.</p>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
