# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: 한재원
title: Back-end Developer
email: point1054@naver.com
phone: 010-4593-1737
website: dodo1054.tistory.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  han-archon

# About Section
about_title: Han Jaewon Introduce
about_profile_image: images/profile.jpg
about_content: | 
  안녕하세요 백엔드 개발자로 일하고 있는 한재원 입니다. <br>
  협업 시 의사소통과 팀원들 간의 일정 및 업무 공유를 중요하게 생각하고, <br>
  실무를 경험하며 협업능력과 개발능력을 기르고 있습니다. <br>
  
  웹 개발 경험으로는 리팅 성형외과 병원 신규 고객관리프로그램(CRM) 프로젝트 <br>
  시스템 취약점 자동진단 솔루션 유지보수 및 신규 프로젝트 개발을 진행하였으며 <br>  
  앱 백엔드 개발 경험으로는 데이팅 앱 서비스인 아만다, 너랑나랑 및 연권 앱 유지보수 및 신규개발을 진행하였습니다. <br>
  
  긍정적으로 잘 웃는 성격이며 어느 환경에서든 조직에 잘 적응하며 <br>
  새로운 기술에 대해 거부감 없이 접근하고 생각하기 때문에 늘 성장할 수 있는 개발자가 될 수 있습니다.
content:
  - title: Skils # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        description: | # this will include new lines to allow paragraphs
          - <mark>PHP</mark> <mark>Javascript(jQuery)</mark> <mark>Java(SpringBoot)</mark> <mark>Vue</mark>
          - <mark>Nginx</mark> <mark>Apache</mark>
          - <mark>Mysql</mark>   
          - <mark>AWS</mark> <mark>Git</mark> <mark>Jira</mark> <mark>Confluence</mark> <mark>Slack</mark>
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)지란지교에스앤씨
        link: https://www.jiransnc.com/
        sub_title: Junior Web developer
        caption: 2023-10 ~ 현재
        description: | # this will include new lines to allow paragraphs
          <h2> 시스템 취약점 자동진단 솔루션 VADA 3.0 유지보수 및 개발 </h2> 
          <h2> 2023.11 - 현재 </h2>
          <h4> Description </h4>
            <p> 취약점 자동진단 솔루션 안정화 및 추가 기능 개발 하였습니다. </p>
          <h4> Work </h4>
            - 서비스 안정화 및 기능 개선 
            - Slow Query 개선
            - 자사 솔루션 기능과 현대해상 및 대신증권 내부 메신저 기능 연동 API 개발
            - 기타 취약점 기능 개발 
          <h4>Tech Stack</h4>
          - <mark>Java(SpringBoot)</mark> <mark>JavaScript(Jquery)</mark> <mark>CSS</mark> 
          - <mark>MariaDB</mark> 
          - <mark>Kendo UI Framework</mark>  
              

          <br>

          <h2> 시스템 취약점 자동진단 솔루션 VADA 4.0 개발 </h2>  
          <h2> 2024.03 - 현재 </h2> 
          <h4> Description </h4>
            <p> 신규 4.0 취약점 자동진단 솔루션 부분 개발 진행을 하였습니다. </p>
          <h4> Work </h4> 
            - 신규 솔루션 제품 GS 인증획득
            - 신규 솔루션 제품 안정화 
            - 취약점 진단 보고서 기능 개발
          <h4>Tech Stack</h4>
          - <mark>Java(Springboot)</mark> <mark>Vue</mark> <mark>JavaScript</mark>
          - <mark>MariaDB</mark>
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)테크랩스
        link: https://www.techlabs.co.kr/
        sub_title: Junior Backend Developer
        caption: 2021-02 ~ 2023-10
        description: | # this will include new lines to allow paragraphs
          <h2> 하루 3만명 이상이 이용하는 데이팅 앱 아만다, 너랑나랑 및 연권 서비스 운영</h2>
          <h2> 2022.11 - 2023.10 </h2> 
          <h4> Description </h4>
            <p> 아만다, 너랑나랑 및 연권 서비스 사용성 향상을 위해 유지보수 및 API 개선하였습니다.</p>
          <h4> Work </h4>
            - 기존 FTP -> API 코드 형상관리를 위한 Git 적용 
            - 쿠폰 이벤트 기능 API 개발 
            - 쿠팡 오퍼월 API 개발 
            - 각각 흩어져 있는 푸시 전송 기능 함수화 하여 관리 포인트 줄임
            - 너랑나랑 및 연권 AWS -> IDC 서버이전 (Mysql 5.6 -> 8.0 Migration, API 및 CMS 서버 분리) 
            - Slow Query 튜닝 통계 운영 웹 페이지 회원 검색 속도 개선
            - CMS 운영 (문의 및 앱내 버그) 사용성 개선 
            - 앱 서비스 안정화 및 개선 (유지보수)
          
          <h4>Tech Stack</h4>
          - <mark>PHP</mark> <mark>JavaScript</mark> <mark>Nginx</mark> <mark>Apache</mark> 
          - <mark>Mysql</mark> <mark>AWS</mark> <mark>Zeppelin</mark>

          <br>

          <h2> 리팅성형외과 고객관리 프로그램 개발 하였으며 하루 약 1000 건 정도의 예약방문 고객과 <br>
               관리자 동시접속 약 200명 병원 납품</h2>  
          <h2> 2021.05 - 2022.09 </h2> 
          <h4> Description </h4>
            <p> 리팅성형외과 병원고객관리 프로그램 프로젝트 신규 개발 및 유지보수</p>
          <h4> Work </h4>
            - 예약, 상담, 진료, 수납 연동 Flow API 개발
            - 예약, 상담, 진료, 수납 고객 관련 통계 페이지 개발   
            - 비즈뿌리오 SMS API 개발 및 병원 서비스 내 예약관리 기능과 연동하여 
              구환 고객 및 신환 고객 SMS 자동화
            - 한국정보인증 전자서명 API 개발 및 병원 서비스 진료관리 기능과 연동하여
              진료의사 간편 서명 기능 제공
            - 혼자서 AWS 클라우드 서버 구성 [EC2, RDS, ELB, route53, AutoScaling, S3] 으로
              프로젝트 개발/운영 서버 환경 구성 및 구축 
            - 병원 서비스 내 고객 차트 및 이미지 AWS S3 스토리지 연동 API 개발 [Upload, Read, Copy, Delete] 
            - ERD 관리 및 일부기능 DB 설계 참여
            - 기존 병원에서 운영했던 프로그램 내 약 150만 건의 병원 Data Migration 자동화 스크립트 개발
              레거시 DB 테이블, 데이터 한글 -> 코드값 변환 및 신규 관리 테이블 동기화 
            - 프로젝트 일정 관리 및 Git 도입으로 (git action) CI/CD 진행
          <h4>Tech Stack</h4>
          - <mark>PHP</mark> <mark>JavaScript</mark> <mark>CSS</mark> <mark>Apache</mark> 
          - <mark>Mysql</mark> <mark>AWS</mark> <mark>Kendo UI Framework</mark>

          <br>
          
          <h2> 리팅성형외과 구환관리 통계 페이지 개발 완료하여 병원 실적 보고서 데이터기반으로 쓰이고 있음 </h2> 
          <h2> 2021.04 - 2021.05 </h2>
          <h4> Description </h4>
            <p> 리팅성형외과 구환(병원 진료 고객) 관리자 페이지 신규 개발</p>
          <h4> Work </h4>
            - 관리자 매출 통계 페이지 개발
            - 관리자 진료, 상담, 콜, 수납 통계 페이지 개발
            - 고객 진료일 및 수술일 관련 통계 페이지 개발 
          <h4>Tech Stack</h4>
          - <mark>PHP</mark> <mark>JavaScript</mark> <mark>CSS</mark> 
          -  <mark>Kendo UI Framework</mark>  
  - title: Projects # Title for the section 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)이엔에스 
        link: http://www.ens-km.co.kr/
        sub_title: Engineer
        caption: 2018-03 ~ 2021-01
        description: | # this will include new lines to allow paragraphs
          <h2> LG 장비 부하 테스트 장비 개발하여 LG에 납품  </h2> 
          <h2> 2020.12 - 2021.01 </h2>
          <h4> Description </h4>
            <p> C# 이용하여 LG 부하 테스트 장비 개발</p>
          <h4> Work </h4>
            - 예약 시간 설정에 따라 자동으로 부하테스트 서비스 개발
            - 장비 별 부하 테스트 ON, OFF 기능 개발
          <h4>Tech Stack</h4>
          - <mark>C#</mark> <mark>JavaScript</mark> 
          - <mark>MariaDB</mark>          

          <br>

          <h2> 계열사 내 경주 태양광 발전소 시스템 환경 구축 및 개발 </h2>  
          <h2> 2020.01 - 2020.12 </h2> 
          <h4> Description </h4>
            <p> 태양광 발전소 시스템 환경 구축 및 장비 관리 시스템 개발 </p>
          <h4> Work </h4> 
            - C# 윈폼 사용하여 장비 내 데이터 뷰 개발 
            - Flex 4 이용하여 관제 모니터링 시스템 구축 
            - 현장 내 에너지 모니터링 시스템 서버 구축
            - 현장 내 LAN 및 RTU 통신 환경 구축 
          <h4>Tech Stack</h4>
          - <mark>C#</mark> <mark>Window</mark> <mark>Flex4</mark> 
          - <mark>MariaDB</mark>

          <br>

          <h2> KT ESS 에너지 모니터링 시스템 </h2>
          <h2> 2018-03 - 2019.12  </h2> 
          <h4> Description </h4>
            <p> 총 8개의 KT ESS 에너지 모니터링 시스템 환경 구축 및 유지보수 하였습니다.</p>
          <h4> Work </h4>
            - CentOS7 기반 Spring 및 Apache 서버 환경 구축 
            - 현장 내 에너지 모니터링 시스템 서버 구축 
            - 현장 내 LAN 및 RTU 통신 환경 구축
          <h4>Tech Stack</h4>
          - <mark>Java</mark> <mark>CentsOS7</mark>

  - title: ETC # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Blog 
        link: dodo1054.tistory.com
        sub_title: 개인 기록용 블로그
        caption: 2019 ~ 현재
        description: |
          <p> 블로그를 한번 헤볼까? 라는 생각으로 개인 기록용으로 사용하고 운영하는 블로그 입니다. <br>
              개인적으로 실천했던 부분들이나 개발하면서 기록이 필요하다고 생각되는 부분들을 기록하고 <br>
              다른 사람들이 참고하여 도움을 줄 수 있도록 만들기 위해 노력하고 있습니다.</p>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
